### ISSUE TITLE
Upload the Chadev logo without brackets as a "small" version

### ISSUE THREAD

**Issue by vendion** [chadev/style-guide#1]
I still like the smaller bracketless logo that was thrown together for the GitHub Org, Maybe  rename the version as the bracket as "large" then add the bracketless one as a "small".  Then we can document usage guidelines stating that the "large" is the official logo and the "small" is for social media/profiles pictures/Gravators/any place where they expect a square image ranging from 50x50 to 100x100 pixels.  Just my $0.02.

**Comment by kylegordy** [comment]
Agreed, it needs to be included as well. I was thinking about throwing the small logo into it's own folder called avatar or icon or something. What do you think? I kind of like keeping it out of the main logo folder to avoid confusion.

**Comment by vendion** [comment]
Having a avatar folder for it works as well.

**Comment by kylegordy** [comment]
Ok cool, folder it is :) You ok with "Avatar" as folder name? I can't think of anything more semantic at the moment…

**Comment by vendion** [comment]
"Avatar" is shorter than "Profile Icon" and they are pretty much used
interchangeably so I don't see a problem with it.

**Comment by kylegordy** [comment]
Ok cool, I'll go ahead and push it up then. Thanks man :+1:

**Comment by vendion** [comment]
No problem!

**Comment by kylegordy** [comment]
Avatars are now go via eca51bea2f1120c5be77e56c48ec2b3cf6993b47 :) I'm going to go ahead and close this issue.

**Comment by vendion** [comment]
Nice, thanks!

**Comment by kylegordy** [comment]
No problem!
