### ISSUE TITLE
Branding and Style questions

### ISSUE THREAD

**Issue by vendion** [chadev/style-guide#2]
These are a few good questions that were originally added to the branding.md file.  Bringing them over here as this is a better place for them, and it facilitates discussions easier.  An FAQ may be good to start latter down the road though.
-   The logo includes brackets, however I'm not sure we want to try to use that everywhere. Opinions?
-  We should set a preference order list as far the availability of alternate names on various social media outlets, i.e.: 
  1.  chadev
  2.  chadevs
  3.  chatdev
  4.  etc, or none of the above.

**Comment by vendion** [comment]
I think the first bullet point falls under issue #1 the logo with brackets in the official logo, and where that does not fit the one that was made for the the Github organisation can be used.

As for the second point I'm okay with that order, only thing I would probably change is instead of chatdev we go with chattdevs unless Adam, Blardo, and them still want to do something under that name.

**Comment by kylegordy** [comment]
I agree with using the "avatar logo" as a fallback when needed. Specifically when the main logo gets too small to read in its given space.

I also agree with @vendion about chattdevs.

**Comment by keathley** [comment]
I'm fine with falling back to chattdevs.  We already have the domain/twitter for that anyway

**Comment by kylegordy** [comment]
@spyc3r did you mean [@chadevs on twitter](https://twitter.com/chadevs)? I think chadevs would work well for us since we can't get chadev :( What does everyone else think? I've already parked [chadev on google plus](https://plus.google.com/u/0/b/103401260409601780643/103401260409601780643/about)… If anyone wants to start building that out let me know. I've done almost nothing with it thus far.

Also, I'm ready to switch chattdevs.com over to chadev.com if your still cool with it? I bought the domain via [hover.com](http://hover.com) if that helps. We can move it though if needed.

**Comment by keathley** [comment]
Yes, I have @chadevs on twitter.  I'll message you tomorrow about moving over the domain.  Should be as simple as pointing the dns at the heroku app.

**Comment by vendion** [comment]
@kylegordy I can help out with the G+ page, feel free to make me a manager on the page if that is okay.  It would be nice to have a official site behind the Chadev name.  Do we need to add a link to the sub-reddit page to the website?

**Comment by kylegordy** [comment]
@spyc3r Awesome, sounds good! :+1:

**Comment by keathley** [comment]
@kylegordy No prob.

@vendion We should definitely add a link to the subreddit on all sites.

**Comment by vendion** [comment]
@spyc3r agreed

**Comment by vendion** [comment]
Change of topic slightly, not sure if I should open a different issue for this.  I added the colors from the logo to the README.md file for documentation reasions.  If I got the colors wrong @kylegordy feel free to correct it, also do we want to have secondary colors?

**Comment by kylegordy** [comment]
@vendion Awesome, thanks man! I just added a color swatch to the repo to help things out. My numbers are a little different than yours though. I can edit them real quick if you want, or should we just link to the [swatch image](https://raw.githubusercontent.com/chadev/style-guide/master/Graphics/Colors/Colors.png)?

**Comment by vendion** [comment]
The color swatches should work, old about the difference in the hex
values.  The numbers I posted where from the pdf I imported into Gimp which
could be the problem.

**Comment by kylegordy** [comment]
@vendion Hmmm, that's strange… Well, I just updated the readme with the image. You dig it?

**Comment by vendion** [comment]
Works for me

**Comment by vendion** [comment]
Closing this issue as it hasn't been touched in a while.
