### ISSUE TITLE
We should put the content in this repo under a Licensce

### ISSUE THREAD

**Issue by vendion** [chadev/style-guide#3]
Our style guide and logos should be under a permissible license, [Creative Commons](http://en.wikipedia.org/wiki/Creative_Commons_license) unless someone can think of something better.

The benefits the Creative Commons has include:
-  Focused on media from the start unlike licenses like the GPL, BSD, MIT, Apache Public License, Mozilla Public License, etc which are geared towards software.
- Easy to understand description of what their licenses mean, so you don't need a law degree to understand them (the legal text that lawyers would require is provided if it ever comes to that).
- Very flexible terms, they have versions that allow for redistribution, and even remixing the original work with attribution.
- Easy UI to find the license that works for your project http://creativecommons.org/choose/
- The "Share-alike" license is a [Copyleft](http://en.wikipedia.org/wiki/Copyleft) license 

That said, I would suggest using the [Attribution-ShareAlike 4.0 International](http://creativecommons.org/licenses/by-sa/4.0/) or [Attribution-NonCommercial-ShareAlike 4.0 International](http://creativecommons.org/licenses/by-nc-sa/4.0/).

**Comment by kylegordy** [comment]
Agreed, I'm game with Attribution ShareAlike license. Feel free to go ahead and apply it if you want.

**Comment by kylegordy** [comment]
Thanks man!

**Comment by vendion** [comment]
No problem!
