### ISSUE TITLE
Branding documentation.

### ISSUE THREAD

**Issue by acedrew** [chadev/style-guide#4]
## Let's get this stuff defined, so that we don't go out doing things randomly on our own.

We should have our resources here too, logos, style guides, etc.

**Comment by kylegordy** [comment]
Agreed, I'll start working on this in a few.

**Comment by kylegordy** [comment]
Hey everyone, I created a [style guide repo](https://github.com/chadev/style-guide) and added the logo files to it. I'll start rounding up other graphics to include in the repo.

**Comment by vendion** [comment]
I feel the branding.md file better falls under the style guide repo as well.

**Comment by vendion** [comment]
Moved this to the style-guide repo, and closing due to age. Feel free to reopen if further action is still needed.
